.PHONY: all build clean test copy iwyu

all: copy

build:
	ninja -C build

clean:
	ninja -C build clean

test:
	ninja -C build test

copy: build
	ssh duke -C pkill -9 -f river-xmonadwm || true
	scp build/river-xmonadwm duke:bin

iwyu: build
	iwyu-tool -p build/compile_commands.json -- -Xiwyu --no_comments -Xiwyu --no_fwd_decls

